# render.yaml
services:
  - type: web
    name: nexus-backend
    runtime: golang
    region: oregon
    buildCommand:
      os: ubuntu
      buildCommand: |
        go mod download
        go build -o nexus
    startCommand: ./nexus
    envVars:
      - key: PORT
        value: 8080
      - key: DEEPSEEK_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    plan: free

  - type: web
    runtime: static
    staticPublishPath: frontend    
    name: nexus-frontend
