# render.yaml
services:
  - type: web
    name: nexus-backend
    runtime: docker
    region: oregon
    buildCommand: |
      go mod download
      go build -o nexus
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: DEEPSEEK_API_KEY
        sync: false
    autoDeploy: true
    plan: free

  - type: web
    runtime: static
    staticPublishPath: frontend    
    name: nexus-frontend
